ensure CarMultihashIterator sorts CIDs by offset
The provider needs the CIDs to be in deterministic order,
because they are used as part of IPLD nodes to produce more CIDs.

Unfortunately, go-car/v2/index.IterableIndex does not guarantee an
order, let alone any form of determinism.
In particular, the used implementation uses two layers of maps,
so the relative order of differently-sized multihashes was randomized.

We could tighten IterableIndex to require determinism, but it doesn't
seem like a clear win. If we simply require some form of determinism,
the provider could suddenly produce different CIDs if we swap out the
CAR index implementation.

Requiring IterableIndex to follow a strict order, such as by offset,
is another option. However, it doesn't seem good either.
For example, the index implementation used here sorts internally by
multihash algorithm, digest length, and digest content.
So we would need to slow down its ForEach implementation to re-sort.
Finally, making IterableIndex follow the implementation's internal order
doesn't seem sane, as it's too specific to that one implementation.

For now, make CarMultihashIterator buffer all multihashes and sort them
by offset. As a safety guard against future non-determinism, fail loudly
if the order is not followed in Next calls.
Without the fix, one test fails already:

	--- FAIL: TestNewCarSupplier_ReturnsExpectedMultihashes (0.00s)
		index_mh_iter_test.go:112:
			Error Trace:	index_mh_iter_test.go:112
			Error:			Received unexpected error:
							car multihash iterator out of order: 368261 then 335061
			Test:			TestNewCarSupplier_ReturnsExpectedMultihashes

To be extra sure, we also error if two offsets are equal.
A CAR index can have duplicate multihashes, but not offsets.

Note that this refactor renders the current CarMultihashIterator API
rather pointless, as we no longer use a background goroutine.
I've left TODOs to clean that up.
For now, we want this fix merged sooner than later, to fix frequent
provider bugs.